[package]
name = "lobsters-retrawled"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.0", features = ["serde"] }
clap = "2.25.0"
failure = "0.1"
flurry = "0.3"
futures-core = "0.3.0"
futures-util = "0.3.0"
hdrhistogram = "7"
itertools = "0.9"
mysql_async = "0.23.0"
nom-sql = "0.0.11"
num_cpus = "1"
rand = "0.7"
rand_distr = "0.2"
regex = "1.0.0"
slog = "2.4.0"
slog-term = "2.4.0"
tokio = { version = "0.2.0", features = ["full"] }
tokio-test = "0.2.0"
tower-service = "0.3.0"
tower-limit = "0.3.1"
# need 0.3.1 for https://github.com/tower-rs/tower/pull/427
tower-util = "0.3.1"
trawler = "0.11.0-alpha.7"
vec_map = { version = "0.8.0" }
zipf = "6"
