{
 "title": "Lobsters metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasoource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Lobsters page loads / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(lobsters_page_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Lobsters page load - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobsters_page{quantile=\"0.5\"}"
    }
   ]
  },
  {
   "title": "Lobsters page load - p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobsters_page{quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "Lobsters page load - p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobsters_page{quantile=\"0.99\"}"
    }
   ]
  }
 ]
}